export const mockedProducts = [
    {
        id: 1,
        category: "vestimenta",
        name: "Buzo canguro",
        description: "Buzo polar para invierno de color negro",
        stock: "Cantidad: " + 50,
        price: "Precio: $" + 15000,
    },
    {
        id: 2,
        category: "vestimenta",
        name: "Zapatillas urbanas",
        description: "Zapatillas estilo Jhon foos",
        stock: "Cantidad: " + 45,
        price: "Precio: $" + 8500,
    },
    {
        id: 3,
        category: "accesorio",
        name: "Billetera",
        description: "Billetera unisex de distintos colores de cuero",
        stock: "Cantidad: " + 30,
        price: "Precio: $" + 4600,
    },
    {
        id: 4,
        category: "medicinales",
        name: "Hiervas medicinales",
        description: "Bolsas de hiervas medicinales para hacer Té o otras infuciones",
        stock: "Cantidad: " + 60,
        price: "Precio: $" + 1500,
    },
    {
        id: 5,
        category: "accesorio",
        name: "Cintos",
        description: "Cintos de cuero con tachas para motoqueros",
        stock: "Cantidad: " + 30,
        price: "Precio: $" + 3500,
    },
    {
        id: 6,
        category: "vestimenta",
        name: "Remera VANS",
        description: "Remera VANS de hombre, ideal para deportes",
        stock: "Cantidad: " + 20,
        price: "Precio: $" + 5700,
    },
    {
        id: 7,
        category: "medicinales",
        name: "Aceites medicinales",
        description: "Aceites de cannabis para ayuda terapeutica",
        stock: "Cantidad: " + 10,
        price: "Precio: $" + 15000,
    },
]